version: 2
updates:
  # dependabot for GitHub Actions for this repo
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(deps):"

  # dependabot for GitHub Actions for the template
  - package-ecosystem: "github-actions"
    directory: "template/.github/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(deps):"
